### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by 0xOkita** [OracleFinder/ChainlinkEthFailover#2]
`2019-08-06T21:21:45Z [WARN]  Failed to connect to ethereum node wss://localhost:80/ services/head_tracker.go:189 err=TxManager#SubscribeToNewHeads: dial tcp 127.0.0.1:80: connect: connection refused errVerbose=dial tcp 127.0.0.1:80: connect: connection refused
TxManager#SubscribeToNewHeads
github.com/smartcontractkit/chainlink/core/services.(*HeadTracker).subscribeToHead
        /go/src/github.com/smartcontractkit/chainlink/core/services/head_tracker.go:238
github.com/smartcontractkit/chainlink/core/services.(*HeadTracker).subscribe
        /go/src/github.com/smartcontractkit/chainlink/core/services/head_tracker.go:187
github.com/smartcontractkit/chainlink/core/services.(*HeadTracker).listenForNewHeads
        /go/src/github.com/smartcontractkit/chainlink/core/services/head_tracker.go:164
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
2019-08-06T21:21:45Z [INFO]  Connecting to node wss://localhost:80/ in 2s       services/head_tracker.go:182
2019-08-06T21:21:47Z [WARN]  Failed to connect to ethereum node wss://localhost:80/ services/head_tracker.go:189 err=TxManager#SubscribeToNewHeads: dial tcp 127.0.0.1:80: connect: connection refused errVerbose=dial tcp 127.0.0.1:80: connect: connection refused
TxManager#SubscribeToNewHeads
github.com/smartcontractkit/chainlink/core/services.(*HeadTracker).subscribeToHead
        /go/src/github.com/smartcontractkit/chainlink/core/services/head_tracker.go:238
github.com/smartcontractkit/chainlink/core/services.(*HeadTracker).subscribe
        /go/src/github.com/smartcontractkit/chainlink/core/services/head_tracker.go:187
github.com/smartcontractkit/chainlink/core/services.(*HeadTracker).listenForNewHeads
        /go/src/github.com/smartcontractkit/chainlink/core/services/head_tracker.go:164
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
2019-08-06T21:21:47Z [INFO]  Connecting to node wss://localhost:80/ in 4s       services/head_tracker.go:182
2019-08-06T21:21:51Z [WARN]  Failed to connect to ethereum node wss://localhost:80/ services/head_tracker.go:189 err=TxManager#SubscribeToNewHeads: dial tcp 127.0.0.1:80: connect: connection refused errVerbose=dial tcp 127.0.0.1:80: connect: connection refused
TxManager#SubscribeToNewHeads
github.com/smartcontractkit/chainlink/core/services.(*HeadTracker).subscribeToHead
        /go/src/github.com/smartcontractkit/chainlink/core/services/head_tracker.go:238
github.com/smartcontractkit/chainlink/core/services.(*HeadTracker).subscribe
        /go/src/github.com/smartcontractkit/chainlink/core/services/head_tracker.go:187
github.com/smartcontractkit/chainlink/core/services.(*HeadTracker).listenForNewHeads
        /go/src/github.com/smartcontractkit/chainlink/core/services/head_tracker.go:164
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
`

I tried to change the port but it did not work

**Comment by boxhock** [comment]
Two things:
* You are connecting with secure Websocket (WSS). Is this intentional?
* You are connecting to port 80 and the project is not set up to load custom ports as ENV vars yet. Are you confident that your proxy is actually running on port 80?

Might be useful to also know if you're running this in Docker or directly.

**Comment by 0xOkita** [comment]
That's not my intention. I just tried to see if it worked or not. I run both Docker and node js and they all listened to the port. If I run the command with 1 node, it worked but two or more. I will give a test again.

**Comment by boxhock** [comment]
Hey @0xOkita, could you please confirm if you're still experiencing this issue?
Otherwise I'll close this issue due to inactivity.
